#ifndef PCV_DASHBOARD_HTML_H
#define PCV_DASHBOARD_HTML_H

/* The ENTIRE PacketVelocity live dashboard as one self-contained HTML document.
 *
 * Invariants (enforced by tests/test_http_guard.c):
 *   - ZERO external URLs: no CDN, no web font, no <link>/<img>/<iframe>, no
 *     url() in CSS. Everything is inline.
 *   - The throughput chart is a STATIC inline <svg> with <polyline> nodes whose
 *     `points` attribute is updated via setAttribute - there is NO
 *     createElementNS, so no 'http://www.w3.org/2000/svg' namespace literal
 *     exists to trip the http:// ban.
 *   - All dynamic text is written via textContent, NEVER innerHTML, so a restyle
 *     slip cannot become self-XSS on the loopback page.
 *   - Same-origin fetch('/stats.json') poll (~1 Hz) renders the three panels:
 *     capture health (incl. the prominent drop-rate), protocol mix, flow table.
 *
 * HTML attributes and JS strings use SINGLE quotes throughout so the document
 * embeds in this C double-quoted string literal without escaping.
 */

static const char PCV_DASHBOARD_HTML[] =
"<!doctype html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<meta name='viewport' content='width=device-width, initial-scale=1'>\n"
"<title>PacketVelocity live</title>\n"
"<style>\n"
"  :root{\n"
"    --bg:#0e1116; --panel:#161b22; --panel2:#1b222c; --grid:#2a333f;\n"
"    --ink:#e6edf3; --muted:#8b98a5; --hair:#30363d;\n"
"    --accent:#2bd576; --cyan:#4aa3ff; --amber:#f0a63a; --red:#ff5c5c;\n"
"    --mono:ui-monospace,'SF Mono',Menlo,Consolas,'Liberation Mono',monospace;\n"
"  }\n"
"  *{box-sizing:border-box;}\n"
"  html,body{margin:0;min-height:100%;}\n"
"  body{background:var(--bg);color:var(--ink);font:13px/1.45 var(--mono);padding:16px;}\n"
"  h1{font-size:15px;letter-spacing:2px;text-transform:uppercase;margin:0;}\n"
"  .bar{display:flex;align-items:baseline;gap:12px;border-bottom:1px solid var(--hair);padding-bottom:10px;margin-bottom:14px;}\n"
"  .bar .sub{color:var(--muted);letter-spacing:1px;text-transform:uppercase;font-size:11px;}\n"
"  .bar .status{margin-left:auto;font-size:11px;letter-spacing:1px;text-transform:uppercase;padding:2px 8px;border:1px solid var(--hair);border-radius:3px;color:var(--muted);}\n"
"  .status.ok{color:var(--accent);border-color:var(--accent);}\n"
"  .status.stall{color:var(--amber);border-color:var(--amber);}\n"
"  .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;}\n"
"  .card{background:var(--panel);border:1px solid var(--hair);border-radius:6px;padding:14px;}\n"
"  .card.wide{grid-column:1 / -1;}\n"
"  .card h2{font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:var(--muted);margin:0 0 12px;}\n"
"  .tiles{display:flex;gap:18px;flex-wrap:wrap;}\n"
"  .tile{min-width:110px;}\n"
"  .tile .k{font-size:10px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);}\n"
"  .tile .v{font-size:22px;font-variant-numeric:tabular-nums;margin-top:2px;}\n"
"  .tile .u{font-size:11px;color:var(--muted);margin-left:4px;}\n"
"  .drop{border:1px solid var(--hair);border-radius:6px;padding:12px 16px;background:var(--panel2);min-width:180px;}\n"
"  .drop .k{font-size:10px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);}\n"
"  .drop .v{font-size:34px;font-variant-numeric:tabular-nums;line-height:1.1;margin-top:2px;}\n"
"  .drop .d{font-size:11px;color:var(--muted);margin-top:4px;}\n"
"  .lvl-ok{color:var(--accent);} .lvl-warn{color:var(--amber);} .lvl-bad{color:var(--red);}\n"
"  svg{display:block;width:100%;height:64px;margin-top:12px;background:var(--panel2);border:1px solid var(--hair);border-radius:4px;}\n"
"  .legend{font-size:10px;color:var(--muted);letter-spacing:1px;text-transform:uppercase;margin-top:6px;}\n"
"  .prow{display:grid;grid-template-columns:70px 1fr 120px;align-items:center;gap:10px;margin-bottom:7px;}\n"
"  .prow .name{font-size:11px;letter-spacing:1px;text-transform:uppercase;color:var(--muted);}\n"
"  .track{height:12px;background:var(--panel2);border:1px solid var(--hair);border-radius:3px;overflow:hidden;}\n"
"  .fill{height:100%;width:0;background:var(--cyan);transition:width .3s ease;}\n"
"  .prow .num{text-align:right;font-variant-numeric:tabular-nums;font-size:12px;color:var(--ink);}\n"
"  table{width:100%;border-collapse:collapse;font-size:12px;}\n"
"  th{text-align:left;color:var(--muted);font-weight:normal;font-size:10px;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid var(--hair);padding:6px 8px;}\n"
"  td{padding:6px 8px;border-bottom:1px solid var(--grid);font-variant-numeric:tabular-nums;}\n"
"  td.tuple{font-variant-numeric:normal;color:var(--cyan);}\n"
"  td.name{font-variant-numeric:normal;max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}\n"
"  td.ip{font-variant-numeric:normal;color:var(--cyan);max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}\n"
"  .ep{color:var(--cyan);} .ep.named{color:var(--ink);}\n"
"  .you{display:inline-block;margin-left:6px;font-size:9px;letter-spacing:1px;text-transform:uppercase;padding:0 5px;border:1px solid var(--accent);border-radius:3px;color:var(--accent);}\n"
"  .muted{color:var(--muted);}\n"
"  tr:last-child td{border-bottom:none;}\n"
"  .empty{color:var(--muted);padding:10px 8px;}\n"
"  footer{color:var(--muted);font-size:10px;letter-spacing:1px;text-transform:uppercase;margin-top:16px;}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"  <div class='bar'>\n"
"    <h1>PacketVelocity // LIVE</h1>\n"
"    <span class='sub' id='iface-line'>capture dashboard</span>\n"
"    <span class='status' id='status'>connecting</span>\n"
"  </div>\n"
"  <div class='grid'>\n"
"    <section class='card wide' id='panel-capture'>\n"
"      <h2>Capture Health</h2>\n"
"      <div class='tiles'>\n"
"        <div class='drop'>\n"
"          <div class='k'>Drop rate (interval)</div>\n"
"          <div class='v' id='drop-rate'>--</div>\n"
"          <div class='d' id='drop-detail'>recv 0 / drop 0</div>\n"
"        </div>\n"
"        <div class='tile'><div class='k'>Packets / s</div><div class='v'><span id='pps'>0</span></div></div>\n"
"        <div class='tile'><div class='k'>Throughput</div><div class='v'><span id='mbit'>0</span><span class='u'>Mbit/s</span></div></div>\n"
"        <div class='tile'><div class='k'>Accepted pkts</div><div class='v'><span id='total-pkts'>0</span></div></div>\n"
"        <div class='tile'><div class='k'>Cumulative drops</div><div class='v'><span id='cum-drop'>0</span></div></div>\n"
"      </div>\n"
"      <svg id='spark' viewBox='0 0 600 64' preserveAspectRatio='none'>\n"
"        <polyline id='spark-pps' fill='none' stroke='#4aa3ff' stroke-width='1.5' points=''></polyline>\n"
"        <polyline id='spark-drop' fill='none' stroke='#ff5c5c' stroke-width='1.5' points=''></polyline>\n"
"      </svg>\n"
"      <div class='legend'>blue: packets/s &nbsp;&nbsp; red: drop rate &nbsp;&nbsp; (rolling history)</div>\n"
"    </section>\n"
"    <section class='card' id='panel-proto'>\n"
"      <h2>Protocol Mix</h2>\n"
"      <div id='proto-rows'></div>\n"
"    </section>\n"
"    <section class='card' id='panel-flows'>\n"
"      <h2>Top Live Flows</h2>\n"
"      <table>\n"
"        <thead><tr><th>Flow</th><th>Pkts</th><th>Bytes</th><th>Dur</th></tr></thead>\n"
"        <tbody id='flow-body'><tr><td class='empty' colspan='4'>no active flows yet</td></tr></tbody>\n"
"      </table>\n"
"    </section>\n"
"    <section class='card wide' id='panel-hosts'>\n"
"      <h2>Hosts (by traffic)</h2>\n"
"      <table>\n"
"        <thead><tr><th>IP</th><th>Name</th><th>Pkts</th><th>Bytes</th><th>Last seen</th></tr></thead>\n"
"        <tbody id='hosts-body'><tr><td class='empty' colspan='5'>no hosts yet</td></tr></tbody>\n"
"      </table>\n"
"    </section>\n"
"  </div>\n"
"  <footer id='foot'>loopback only (127.0.0.1) &middot; polling /stats.json</footer>\n"
"<script>\n"
"(function(){\n"
"  'use strict';\n"
"  var PROTOS=[['tcp','TCP'],['udp','UDP'],['icmp','ICMP'],['arp','ARP'],['ipv6','IPv6'],['other','OTHER']];\n"
"  var rowsEl=document.getElementById('proto-rows');\n"
"  var fills={}, counts={};\n"
"  PROTOS.forEach(function(p){\n"
"    var row=document.createElement('div'); row.className='prow';\n"
"    var name=document.createElement('div'); name.className='name'; name.textContent=p[1];\n"
"    var track=document.createElement('div'); track.className='track';\n"
"    var fill=document.createElement('div'); fill.className='fill'; track.appendChild(fill);\n"
"    var num=document.createElement('div'); num.className='num'; num.textContent='0';\n"
"    row.appendChild(name); row.appendChild(track); row.appendChild(num);\n"
"    rowsEl.appendChild(row); fills[p[0]]=fill; counts[p[0]]=num;\n"
"  });\n"
"  function fmtInt(n){ n=Math.round(n||0); var s=String(n),o='',c=0,i; for(i=s.length-1;i>=0;i--){o=s[i]+o; if(++c%3===0 && i>0)o=','+o;} return o; }\n"
"  function fmtBytes(n){ n=n||0; var u=['B','KB','MB','GB','TB'],i=0; while(n>=1024 && i<u.length-1){n/=1024;i++;} return (i===0?n:n.toFixed(1))+' '+u[i]; }\n"
"  function fmtDur(ms){ ms=ms||0; if(ms<1000)return Math.round(ms)+'ms'; var s=ms/1000; if(s<60)return s.toFixed(1)+'s'; var m=Math.floor(s/60); return m+'m'+Math.round(s-m*60)+'s'; }\n"
"  function fmtAge(ns){ if(!(ns>0))return '-'; var s=ns/1e9; if(s<1)return '<1s'; if(s<60)return Math.round(s)+'s'; var m=Math.floor(s/60); if(m<60)return m+'m'+Math.round(s-m*60)+'s'; var h=Math.floor(m/60); return h+'h'+(m-h*60)+'m'; }\n"
/* Build one endpoint element: prefer the resolved NAME, keep the raw IP in a
 * title (set via setAttribute, never innerHTML), tag the local host. All text
 * is written with textContent so an attacker-influenced name is inert. */
"  function endpoint(ip,port,name,local){\n"
"    var span=document.createElement('span'); span.className='ep';\n"
"    var label=(name&&name.length)?name:ip; if(name&&name.length)span.className='ep named';\n"
"    span.textContent=label+':'+port;\n"
"    span.setAttribute('title',ip+':'+port);\n"
"    var frag=document.createDocumentFragment(); frag.appendChild(span);\n"
"    if(local&&ip===local){ var b=document.createElement('span'); b.className='you'; b.textContent='you'; frag.appendChild(b); }\n"
"    return frag;\n"
"  }\n"
"  function setLevel(el,ratio){ el.classList.remove('lvl-ok','lvl-warn','lvl-bad'); if(ratio>=0.01)el.classList.add('lvl-bad'); else if(ratio>=0.001)el.classList.add('lvl-warn'); else el.classList.add('lvl-ok'); }\n"
"  function poly(hist,key,w,h,fixedMax){\n"
"    if(!hist||!hist.length)return '';\n"
"    var max=fixedMax||0; var i; if(!fixedMax){ for(i=0;i<hist.length;i++){ if(hist[i][key]>max)max=hist[i][key]; } }\n"
"    if(max<=0)max=1; var n=hist.length; var pts=''; \n"
"    for(i=0;i<n;i++){ var x=(n===1)?0:(i*w/(n-1)); var y=h-(hist[i][key]/max)*(h-4)-2; pts+=(i?' ':'')+x.toFixed(1)+','+y.toFixed(1); }\n"
"    return pts;\n"
"  }\n"
"  var statusEl=document.getElementById('status');\n"
"  var misses=0;\n"
"  function render(d){\n"
"    document.getElementById('pps').textContent=fmtInt(d.capture.pps);\n"
"    document.getElementById('mbit').textContent=(d.capture.mbit||0).toFixed(2);\n"
"    document.getElementById('total-pkts').textContent=fmtInt(d.pkts);\n"
"    document.getElementById('cum-drop').textContent=fmtInt(d.capture.dropped);\n"
"    var dr=document.getElementById('drop-rate');\n"
"    dr.textContent=((d.capture.drop_rate||0)*100).toFixed(3)+'%';\n"
"    setLevel(dr,d.capture.drop_rate||0);\n"
"    document.getElementById('drop-detail').textContent='interval recv '+fmtInt(d.capture.recv)+' / drop '+fmtInt(d.capture.dropped)+' (cum '+((d.capture.drop_ratio||0)*100).toFixed(3)+'%)';\n"
"    var total=d.proto_total||0;\n"
"    PROTOS.forEach(function(p){ var c=(d.proto&&d.proto[p[0]])||0; counts[p[0]].textContent=fmtInt(c)+(total? '  '+((c/total)*100).toFixed(1)+'%':''); fills[p[0]].style.width=(total?(c/total)*100:0)+'%'; });\n"
"    document.getElementById('spark-pps').setAttribute('points',poly(d.history,'pps',600,64,0));\n"
"    document.getElementById('spark-drop').setAttribute('points',poly(d.history,'drop_rate',600,64,1));\n"
"    var local=d.local||'';\n"
"    var body=document.getElementById('flow-body');\n"
"    while(body.firstChild)body.removeChild(body.firstChild);\n"
"    var flows=d.flows||[];\n"
"    if(!flows.length){ var tr=document.createElement('tr'); var td=document.createElement('td'); td.className='empty'; td.setAttribute('colspan','4'); td.textContent='no active flows yet'; tr.appendChild(td); body.appendChild(tr); }\n"
"    else { flows.forEach(function(f){ var tr=document.createElement('tr');\n"
"      var a=document.createElement('td'); a.className='tuple';\n"
"      if(f.src_ip!==undefined){ a.appendChild(endpoint(f.src_ip,f.src_port,f.src_name,local)); var arrow=document.createElement('span'); arrow.className='muted'; arrow.textContent=' \\u2192 '; a.appendChild(arrow); a.appendChild(endpoint(f.dst_ip,f.dst_port,f.dst_name,local)); a.setAttribute('title',f.tuple||''); }\n"
"      else { a.textContent=f.tuple; }\n"
"      var b=document.createElement('td'); b.textContent=fmtInt(f.packets);\n"
"      var c=document.createElement('td'); c.textContent=fmtBytes(f.bytes);\n"
"      var e=document.createElement('td'); e.textContent=fmtDur(f.duration_ms);\n"
"      tr.appendChild(a);tr.appendChild(b);tr.appendChild(c);tr.appendChild(e); body.appendChild(tr); }); }\n"
"    var hbody=document.getElementById('hosts-body');\n"
"    while(hbody.firstChild)hbody.removeChild(hbody.firstChild);\n"
"    var hosts=d.hosts||[]; var now=d.now_ns||0;\n"
"    if(!hosts.length){ var htr=document.createElement('tr'); var htd=document.createElement('td'); htd.className='empty'; htd.setAttribute('colspan','5'); htd.textContent='no hosts yet'; htr.appendChild(htd); hbody.appendChild(htr); }\n"
"    else { hosts.forEach(function(h){ var tr=document.createElement('tr');\n"
"      var ip=document.createElement('td'); ip.className='ip'; ip.textContent=h.ip; if(local&&h.ip===local){ var b=document.createElement('span'); b.className='you'; b.textContent='you'; ip.appendChild(b); }\n"
"      var nm=document.createElement('td'); nm.className='name'; if(h.name&&h.name.length){ nm.textContent=h.name; nm.setAttribute('title',h.name); } else { nm.className='name muted'; nm.textContent='\\u2014'; }\n"
"      var pk=document.createElement('td'); pk.textContent=fmtInt(h.pkts);\n"
"      var by=document.createElement('td'); by.textContent=fmtBytes(h.bytes);\n"
"      var ls=document.createElement('td'); ls.textContent=fmtAge(now-(h.last_seen||0));\n"
"      tr.appendChild(ip);tr.appendChild(nm);tr.appendChild(pk);tr.appendChild(by);tr.appendChild(ls); hbody.appendChild(tr); }); }\n"
"  }\n"
"  function tick(){\n"
"    fetch('/stats.json',{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){\n"
"      misses=0; statusEl.textContent='live'; statusEl.className='status ok'; render(d);\n"
"    }).catch(function(){ misses++; if(misses>=2){ statusEl.textContent='stalled'; statusEl.className='status stall'; } });\n"
"  }\n"
"  tick(); setInterval(tick,1000);\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* PCV_DASHBOARD_HTML_H */
